#!/usr/bin/env bash

## This script will queue 5 model fits and 4 calibrations, this was
## written for naomi-preview, if you want to run from a different
## machine you need to ensure that the files in the payload
## exist at the right path and that the API can be found
## at localhost:8888


set -eux

for i in {1..5}
do
	curl -X POST \
		-H "Content-Type: application/json" \
		-d @zim_payload.json \
       		localhost:8888/model/submit
done

echo "\nQueued 5 Zimbabwe model fits"

for i in {1..3}
do
	curl -X POST \
		-H "Content-Type: application/json" \
		-d @calibrate_payload.json \
		localhost:8888/model/calibrate/a4b357eae31aa31177c1defb08ec0473
done

echo "\nQueued 3 calibrations"
